# Generated by Django 2.2.4 on 2019-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='city',
            field=models.CharField(default='Delhi', max_length=100),
        ),
    ]
