# Generated by Django 2.2.4 on 2019-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_show_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedian',
            name='imgUrl',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='show',
            name='imgUrl',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comedian',
            name='linkedinUrl',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comedian',
            name='websiteUrl',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comedian',
            name='youtubeUrl',
            field=models.URLField(max_length=1000),
        ),
    ]
